# Generated by Django 4.0 on 2022-06-12 14:32

from django.db import migrations


def create_typeoffood(apps, schema_editor):
    type_of_foods = ["mexican", "italian", "indian", "cajun", "soul",
    "thai","greek", "chinese","vegan","lebanese",
    "japanese","american","moroccan","mediterranean","french",
    "spanish", "german","korean","vietnamese","turkish","caribbean"]
    TypeOfFood = apps.get_model('food_review', 'TypeOfFood')
    
    TypeOfFood.objects.bulk_create([TypeOfFood(type_of_food = tof) for tof in type_of_foods])

def create_tags(apps, schema_editor):
    tags = ["vegan", "spicy", "ovo lacto", "gluten-free", 
    "family style", "breakfast", "lunch", "dinner",
    "dessert","happy hour","paleo"]
    Tag = apps.get_model('food_review', 'Tag')
    Tag.objects.bulk_create([Tag(tag_name=t) for t in tags])



    


class Migration(migrations.Migration):

    dependencies = [
        ('food_review', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_typeoffood),
        migrations.RunPython(create_tags)
    ]
